builders:
  googleable:
    import: 'package:googleable/src/googleable_builder.dart'  #build文件
    builder_factories: ['googleable']
    build_extensions: {'.dart': ['.po']}
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen|combining_builder"]
